server:
  port: 8088
spring:
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    #ollama:
   #   base-url: http://localhost:11434
   #   chat:
   #     options:
    #      model: mistral:7b
     #     temperature: 0.1
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}
    username: ${ADMIN}
    password: ${SIMPLE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  pattern:
    console: '%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - ${LOG_LEVEL_PATTERN:-%5p} %m%n'